{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n>       assert False\nE       assert False\n\nlecture_29/test_allure.py:27: AssertionError"}, "start": 1720201825806, "stop": 1720201825807, "uuid": "7697decd-3e38-4427-8fb4-f1709d0a1984", "historyId": "bee06c0f8fdaa9559c38e5d55c0c7913", "testCaseId": "bee06c0f8fdaa9559c38e5d55c0c7913", "fullName": "lecture_29.test_allure#test_failure", "labels": [{"name": "parentSuite", "value": "lecture_29"}, {"name": "suite", "value": "test_allure"}, {"name": "host", "value": "vostro5402"}, {"name": "thread", "value": "38029-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "lecture_29.test_allure"}]}